# - name: install epel repo
#   yum:
#     name: "{{ epel_repo_url }}"
#     state: present
#   tags:
#     - epel

# - name: import epel gpg key
#   rpm_key:
#     key: "{{ epel_repo_gpg_key_path }}"
#     state: present
#   tags:
#     - epel

- name: Install epel repo
  yum: name=epel-release state=latest
  when: ansible_pkg_mgr == "yum" and ansible_distribution == 'CentOS'


- name: Check for not installing epel repo
  fail: msg="Unsupported OS!"
  when: ansible_pkg_mgr != "yum" or ansible_distribution != 'CentOS'


# Note: https://fedoraproject.org/wiki/EPEL
