---

# deploy ssh key and make sudo work without password

# install 'sshpass' package first on your local system

# ssh -o UserKnownHostsFile=./known_hosts <user>@<host>
# ansible all --ask-pass --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -m ping -i <host>, -u <username>
#                                                                                               ^^^ the comma is required
# ansible-playbook -i <host>, -u <username> --ask-pass --ask-become-pass --ssh-common-args='-o UserKnownHostsFile=./known_hosts' install-ansible-prereqs.yml
#                          ^^^ the comma is required
# rm -f ./known_hosts

- hosts: all
  become: no
  gather_facts: False
  tasks:
    - name: create ssh directory
      file: path=.ssh state=directory mode=0700

    # this will OVERWRITE existing ssh keys!
    - name: install ssh key
      copy: src=~/.ssh/id_rsa.pub dest=.ssh/authorized_keys mode=0700

- hosts: all
  become: yes
  tasks:
    - name: add group to /etc/sudoers file without password
      lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

